      SUBROUTINE NATCRZ (IWHO)
      IMPLICIT NONE
C----------
C  $Id: natcrz.f 767 2013-04-10 22:29:22Z rhavis@msn.com $
C----------
C
C     CREATE A FILE FOR PROCESSING THROUGH THE NATIONAL CRUISE SYSTEM
C     VOLUME ROUTINE
C
C     IWHO=1 IF CALLED FROM MAIN, IWHO=2 IF CALLED FROM CUTS
C     **THIS VERSION IS A STUB: NATCRZ NOTE USED IN BC**
C
      INTEGER IWHO
      RETURN
	END
