      SUBROUTINE EXMPB
      IMPLICIT NONE
C----------
C  $Id: exmpb.f 767 2013-04-10 22:29:22Z rhavis@msn.com $
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR MPB CALLS
C
      LOGICAL L,LNOTBK,LKECHO
      CHARACTER*8 KEYWRD,NOMPB
      CHARACTER*26 NPLT
      DIMENSION LNOTBK(7)
      INTEGER ICODES(6)
      REAL ARRAY(7)
      INTEGER MGMID,II,KEY
C
      DATA NOMPB/'*NO MPB'/
      ENTRY MPBINT
      RETURN
      ENTRY MPBHED (NPLT,MGMID)
      RETURN
      ENTRY MPBIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
      CALL ERRGRO (.TRUE.,11)
      RETURN
      ENTRY MPBDAM (II,ICODES)
      RETURN
      ENTRY MPBOPS
      RETURN
      ENTRY MPBCUP
      RETURN
      ENTRY MPBGO (L)
      L = .FALSE.
      RETURN
      ENTRY MPBOUT
      RETURN
      ENTRY MPSDLP
      RETURN
      ENTRY MPKEY(KEY,KEYWRD)
      KEYWRD=NOMPB
      RETURN
      END
