      SUBROUTINE FORMCL(ISPC,IFOR,D,FC)
      use contrl_mod
      use prgprm_mod
      implicit none
C----------
C  $Id$
C----------
C
C THIS PROGRAM CALCULATES FORM FACTORS FOR CALCULATING CUBIC AND
C BOARD FOOT VOLUMES.
C
C THIS IS THE VANILLA VERSION FOR USE IN VARIANTS THAT DON'T USE
C FORM CLASS, OR ONLY SET DEFAULT FORM CLASSES BY SPECIES.
C
      INTEGER IFOR,ISPC
      REAL FC,D
C
C----------
C  LOAD FORM CLASS VALUE
C----------
      FC=FRMCLS(ISPC)
C
      RETURN
      END
