      BLOCK DATA SVBLKD
      IMPLICIT NONE
C----------
C  $Id: svblkd.f 767 2013-04-10 22:29:22Z rhavis@msn.com $
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     INITIALIZE VISUALIZATION VARIABLES
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'SVDATA.F77'
C
C
COMMONS
C
      DATA NIMAGE/0/
      END
