      SUBROUTINE SVCMP2(ITARG,ISOUR)
      use contrl_mod
      use svdata_mod
      use workcm_mod
      use prgprm_mod
      implicit none
C----------
C  $Id$
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     REGISTER MOVEMENTS OF TREE RECORDS WITH THE VISUALIZATION DATA
C
C     INPUT:
C     ITARG IS A TARGET LOCATION TO WHICH A TREE WILL BE PLACED
C     ISOUR IS THE INDEX OF THE TREE BEING MOVED.
C
C     CALLED FROM COMPRS AND TREDEL.
C
      INTEGER ISOUR,ITARG
C
      IF (JSVOUT.EQ.0) RETURN
C
      IWKCM1(ISOUR)=ITARG
      RETURN
      END
