      SUBROUTINE SVHABT(XMOD)
      IMPLICIT NONE
C----------
C  $Id: svhabt.f 767 2013-04-10 22:29:22Z rhavis@msn.com $
C----------
C
C     STAND VISUALIZATION GENERATION
C     J.J.MARCHINEK -- RMRS MOSCOW -- JUNE 1998
C
C     USED FOR PROCESSING HABITAT INFORMATION FOR SNAGS
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'SVDEAD.F77'
C
C
COMMONS
C
C
      REAL XMOD
      XMOD=1.

      RETURN
      END
