      SUBROUTINE SVHABT(XMOD)
      use prgprm_mod
      implicit none
C----------
C  $Id$
C----------
C
C     STAND VISUALIZATION GENERATION
C     J.J.MARCHINEK -- RMRS MOSCOW -- JUNE 1998
C
C     USED FOR PROCESSING HABITAT INFORMATION FOR SNAGS
C
      INCLUDE 'SVDEAD.F77'
C
      REAL XMOD
      XMOD=1.

      RETURN
      END
