/* File: testmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Dec 23 00:47:05 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *test_error;
static PyObject *test_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = test_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = test_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(fvsSetCmdLine,FVSSETCMDLINE)(string,int*,int*,size_t);
extern void F_FUNC(fvsGetStoppointCodes,FVSGETSTOPPOINTCODES)(int*,int*);
extern void F_FUNC(fvsSetStoppointCodes,FVSSETSTOPPOINTCODES)(int*,int*);
extern void F_FUNC(fvsGetRestartCode,FVSGETRESTARTCODE)(int*);
extern void F_FUNC(clearrestartcode,CLEARRESTARTCODE)(void);
extern void F_FUNC(fvsRestart,FVSRESTART)(int*);
extern void F_FUNC(fvsRestartLastStand,FVSRESTARTLASTSTAND)(int*);
extern void F_FUNC(fvsGetKeywordFileName,FVSGETKEYWORDFILENAME)(string,int*,int*,size_t);
extern void F_FUNC(fvsSetRtnCode,FVSSETRTNCODE)(int*);
extern void F_FUNC(fvsGetRtnCode,FVSGETRTNCODE)(int*);
extern void F_FUNC(fvsStopPoint,FVSSTOPPOINT)(int*,int*);
extern void F_FUNC(getAmStopping,GETAMSTOPPING)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* fvsSetCmdLine *******************************/
static char doc_f2py_rout_test_fvsSetCmdLine[] = "\
IRTNCD = fvsSetCmdLine(theCmdLine)\n\nWrapper for ``fvsSetCmdLine``.\
\n\nParameters\n----------\n"
"theCmdLine : input string(len=-1)\n"
"\nReturns\n-------\n"
"IRTNCD : int";
/* extern void F_FUNC(fvsSetCmdLine,FVSSETCMDLINE)(string,int*,int*,size_t); */
static PyObject *f2py_rout_test_fvsSetCmdLine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string theCmdLine = NULL;
  int slen(theCmdLine);
  PyObject *theCmdLine_capi = Py_None;
  int lenCL = 0;
  int IRTNCD = 0;
  static char *capi_kwlist[] = {"theCmdLine",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:test.fvsSetCmdLine",\
    capi_kwlist,&theCmdLine_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable IRTNCD */
  /* Processing variable theCmdLine */
  slen(theCmdLine) = -1;
  f2py_success = string_from_pyobj(&theCmdLine,&slen(theCmdLine),"",theCmdLine_capi,"string_from_pyobj failed in converting 1st argument `theCmdLine' of test.fvsSetCmdLine to C string");
  if (f2py_success) {
  /* Processing variable lenCL */
  lenCL = slen(theCmdLine);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(theCmdLine,&lenCL,&IRTNCD,slen(theCmdLine));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",IRTNCD);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable lenCL */
    STRINGFREE(theCmdLine);
  }  /*if (f2py_success) of theCmdLine*/
  /* End of cleaning variable theCmdLine */
  /* End of cleaning variable IRTNCD */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of fvsSetCmdLine ****************************/

/**************************** fvsGetStoppointCodes ****************************/
static char doc_f2py_rout_test_fvsGetStoppointCodes[] = "\
spptcd,spptyr = fvsGetStoppointCodes()\n\nWrapper for ``fvsGetStoppointCodes``.\
\n\nReturns\n-------\n"
"spptcd : int\n"
"spptyr : int";
/* extern void F_FUNC(fvsGetStoppointCodes,FVSGETSTOPPOINTCODES)(int*,int*); */
static PyObject *f2py_rout_test_fvsGetStoppointCodes(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int spptcd = 0;
  int spptyr = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsGetStoppointCodes",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable spptyr */
  /* Processing variable spptcd */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&spptcd,&spptyr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ii",spptcd,spptyr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable spptcd */
  /* End of cleaning variable spptyr */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of fvsGetStoppointCodes ************************/

/**************************** fvsSetStoppointCodes ****************************/
static char doc_f2py_rout_test_fvsSetStoppointCodes[] = "\
fvsSetStoppointCodes(spptcd,spptyr)\n\nWrapper for ``fvsSetStoppointCodes``.\
\n\nParameters\n----------\n"
"spptcd : input int\n"
"spptyr : input int";
/* extern void F_FUNC(fvsSetStoppointCodes,FVSSETSTOPPOINTCODES)(int*,int*); */
static PyObject *f2py_rout_test_fvsSetStoppointCodes(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int spptcd = 0;
  PyObject *spptcd_capi = Py_None;
  int spptyr = 0;
  PyObject *spptyr_capi = Py_None;
  static char *capi_kwlist[] = {"spptcd","spptyr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:test.fvsSetStoppointCodes",\
    capi_kwlist,&spptcd_capi,&spptyr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable spptyr */
    f2py_success = int_from_pyobj(&spptyr,spptyr_capi,"test.fvsSetStoppointCodes() 2nd argument (spptyr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable spptcd */
    f2py_success = int_from_pyobj(&spptcd,spptcd_capi,"test.fvsSetStoppointCodes() 1st argument (spptcd) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&spptcd,&spptyr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of spptcd*/
  /* End of cleaning variable spptcd */
  } /*if (f2py_success) of spptyr*/
  /* End of cleaning variable spptyr */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of fvsSetStoppointCodes ************************/

/***************************** fvsGetRestartCode *****************************/
static char doc_f2py_rout_test_fvsGetRestartCode[] = "\
restrtcd = fvsGetRestartCode()\n\nWrapper for ``fvsGetRestartCode``.\
\n\nReturns\n-------\n"
"restrtcd : int";
/* extern void F_FUNC(fvsGetRestartCode,FVSGETRESTARTCODE)(int*); */
static PyObject *f2py_rout_test_fvsGetRestartCode(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int restrtcd = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsGetRestartCode",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable restrtcd */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&restrtcd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",restrtcd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable restrtcd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of fvsGetRestartCode **************************/

/****************************** clearrestartcode ******************************/
static char doc_f2py_rout_test_clearrestartcode[] = "\
clearrestartcode()\n\nWrapper for ``clearrestartcode``.\
\n";
/* extern void F_FUNC(clearrestartcode,CLEARRESTARTCODE)(void); */
static PyObject *f2py_rout_test_clearrestartcode(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.clearrestartcode",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of clearrestartcode **************************/

/********************************* fvsRestart *********************************/
static char doc_f2py_rout_test_fvsRestart[] = "\
restrtcd = fvsRestart()\n\nWrapper for ``fvsRestart``.\
\n\nReturns\n-------\n"
"restrtcd : int";
/* extern void F_FUNC(fvsRestart,FVSRESTART)(int*); */
static PyObject *f2py_rout_test_fvsRestart(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int restrtcd = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsRestart",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable restrtcd */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&restrtcd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",restrtcd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable restrtcd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of fvsRestart *****************************/

/**************************** fvsRestartLastStand ****************************/
static char doc_f2py_rout_test_fvsRestartLastStand[] = "\
restrtcd = fvsRestartLastStand()\n\nWrapper for ``fvsRestartLastStand``.\
\n\nReturns\n-------\n"
"restrtcd : int";
/* extern void F_FUNC(fvsRestartLastStand,FVSRESTARTLASTSTAND)(int*); */
static PyObject *f2py_rout_test_fvsRestartLastStand(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int restrtcd = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsRestartLastStand",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable restrtcd */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&restrtcd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",restrtcd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable restrtcd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of fvsRestartLastStand *************************/

/*************************** fvsGetKeywordFileName ***************************/
static char doc_f2py_rout_test_fvsGetKeywordFileName[] = "\
fn = fvsGetKeywordFileName()\n\nWrapper for ``fvsGetKeywordFileName``.\
\n\nReturns\n-------\n"
"fn : string(len=mxch)";
/* extern void F_FUNC(fvsGetKeywordFileName,FVSGETKEYWORDFILENAME)(string,int*,int*,size_t); */
static PyObject *f2py_rout_test_fvsGetKeywordFileName(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string fn = NULL;
  int slen(fn);
  PyObject *fn_capi = Py_None;
  int mxch = 0;
  int nch = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsGetKeywordFileName",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable nch */
  /* Processing variable fn */
  slen(fn) = mxch;
  f2py_success = string_from_pyobj(&fn,&slen(fn),"",fn_capi,"string_from_pyobj failed in converting hidden `fn' of test.fvsGetKeywordFileName to C string");
  if (f2py_success) {
  /* Processing variable mxch */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(fn,&mxch,&nch,slen(fn));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("y",fn);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable mxch */
    STRINGFREE(fn);
  }  /*if (f2py_success) of fn*/
  /* End of cleaning variable fn */
  /* End of cleaning variable nch */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of fvsGetKeywordFileName ************************/

/******************************* fvsSetRtnCode *******************************/
static char doc_f2py_rout_test_fvsSetRtnCode[] = "\
rtnCode = fvsSetRtnCode()\n\nWrapper for ``fvsSetRtnCode``.\
\n\nReturns\n-------\n"
"rtnCode : int";
/* extern void F_FUNC(fvsSetRtnCode,FVSSETRTNCODE)(int*); */
static PyObject *f2py_rout_test_fvsSetRtnCode(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int rtnCode = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsSetRtnCode",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable rtnCode */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&rtnCode);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",rtnCode);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable rtnCode */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of fvsSetRtnCode ****************************/

/******************************* fvsGetRtnCode *******************************/
static char doc_f2py_rout_test_fvsGetRtnCode[] = "\
rtnCode = fvsGetRtnCode()\n\nWrapper for ``fvsGetRtnCode``.\
\n\nReturns\n-------\n"
"rtnCode : int";
/* extern void F_FUNC(fvsGetRtnCode,FVSGETRTNCODE)(int*); */
static PyObject *f2py_rout_test_fvsGetRtnCode(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int rtnCode = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.fvsGetRtnCode",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable rtnCode */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&rtnCode);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",rtnCode);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable rtnCode */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of fvsGetRtnCode ****************************/

/******************************** fvsStopPoint ********************************/
static char doc_f2py_rout_test_fvsStopPoint[] = "\
ISTOPDONE = fvsStopPoint(LOCODE)\n\nWrapper for ``fvsStopPoint``.\
\n\nParameters\n----------\n"
"LOCODE : input int\n"
"\nReturns\n-------\n"
"ISTOPDONE : int";
/* extern void F_FUNC(fvsStopPoint,FVSSTOPPOINT)(int*,int*); */
static PyObject *f2py_rout_test_fvsStopPoint(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int LOCODE = 0;
  PyObject *LOCODE_capi = Py_None;
  int ISTOPDONE = 0;
  static char *capi_kwlist[] = {"LOCODE",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:test.fvsStopPoint",\
    capi_kwlist,&LOCODE_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ISTOPDONE */
  /* Processing variable LOCODE */
    f2py_success = int_from_pyobj(&LOCODE,LOCODE_capi,"test.fvsStopPoint() 1st argument (LOCODE) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&LOCODE,&ISTOPDONE);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ISTOPDONE);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of LOCODE*/
  /* End of cleaning variable LOCODE */
  /* End of cleaning variable ISTOPDONE */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of fvsStopPoint ****************************/

/******************************* getAmStopping *******************************/
static char doc_f2py_rout_test_getAmStopping[] = "\
ISTOPDONE = getAmStopping()\n\nWrapper for ``getAmStopping``.\
\n\nReturns\n-------\n"
"ISTOPDONE : int";
/* extern void F_FUNC(getAmStopping,GETAMSTOPPING)(int*); */
static PyObject *f2py_rout_test_getAmStopping(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ISTOPDONE = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":test.getAmStopping",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable ISTOPDONE */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ISTOPDONE);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ISTOPDONE);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ISTOPDONE */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of getAmStopping ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"fvsSetCmdLine",-1,{{-1}},0,(char *)F_FUNC(fvsSetCmdLine,FVSSETCMDLINE),(f2py_init_func)f2py_rout_test_fvsSetCmdLine,doc_f2py_rout_test_fvsSetCmdLine},
  {"fvsGetStoppointCodes",-1,{{-1}},0,(char *)F_FUNC(fvsGetStoppointCodes,FVSGETSTOPPOINTCODES),(f2py_init_func)f2py_rout_test_fvsGetStoppointCodes,doc_f2py_rout_test_fvsGetStoppointCodes},
  {"fvsSetStoppointCodes",-1,{{-1}},0,(char *)F_FUNC(fvsSetStoppointCodes,FVSSETSTOPPOINTCODES),(f2py_init_func)f2py_rout_test_fvsSetStoppointCodes,doc_f2py_rout_test_fvsSetStoppointCodes},
  {"fvsGetRestartCode",-1,{{-1}},0,(char *)F_FUNC(fvsGetRestartCode,FVSGETRESTARTCODE),(f2py_init_func)f2py_rout_test_fvsGetRestartCode,doc_f2py_rout_test_fvsGetRestartCode},
  {"clearrestartcode",-1,{{-1}},0,(char *)F_FUNC(clearrestartcode,CLEARRESTARTCODE),(f2py_init_func)f2py_rout_test_clearrestartcode,doc_f2py_rout_test_clearrestartcode},
  {"fvsRestart",-1,{{-1}},0,(char *)F_FUNC(fvsRestart,FVSRESTART),(f2py_init_func)f2py_rout_test_fvsRestart,doc_f2py_rout_test_fvsRestart},
  {"fvsRestartLastStand",-1,{{-1}},0,(char *)F_FUNC(fvsRestartLastStand,FVSRESTARTLASTSTAND),(f2py_init_func)f2py_rout_test_fvsRestartLastStand,doc_f2py_rout_test_fvsRestartLastStand},
  {"fvsGetKeywordFileName",-1,{{-1}},0,(char *)F_FUNC(fvsGetKeywordFileName,FVSGETKEYWORDFILENAME),(f2py_init_func)f2py_rout_test_fvsGetKeywordFileName,doc_f2py_rout_test_fvsGetKeywordFileName},
  {"fvsSetRtnCode",-1,{{-1}},0,(char *)F_FUNC(fvsSetRtnCode,FVSSETRTNCODE),(f2py_init_func)f2py_rout_test_fvsSetRtnCode,doc_f2py_rout_test_fvsSetRtnCode},
  {"fvsGetRtnCode",-1,{{-1}},0,(char *)F_FUNC(fvsGetRtnCode,FVSGETRTNCODE),(f2py_init_func)f2py_rout_test_fvsGetRtnCode,doc_f2py_rout_test_fvsGetRtnCode},
  {"fvsStopPoint",-1,{{-1}},0,(char *)F_FUNC(fvsStopPoint,FVSSTOPPOINT),(f2py_init_func)f2py_rout_test_fvsStopPoint,doc_f2py_rout_test_fvsStopPoint},
  {"getAmStopping",-1,{{-1}},0,(char *)F_FUNC(getAmStopping,GETAMSTOPPING),(f2py_init_func)f2py_rout_test_getAmStopping,doc_f2py_rout_test_getAmStopping},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "test",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_test(void) {
#else
#define RETVAL
PyMODINIT_FUNC inittest(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = test_module = PyModule_Create(&moduledef);
#else
  m = test_module = Py_InitModule("test", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module test (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'test' is auto-generated with f2py (version:2).\nFunctions:\n"
"  IRTNCD = fvsSetCmdLine(theCmdLine)\n"
"  spptcd,spptyr = fvsGetStoppointCodes()\n"
"  fvsSetStoppointCodes(spptcd,spptyr)\n"
"  restrtcd = fvsGetRestartCode()\n"
"  clearrestartcode()\n"
"  restrtcd = fvsRestart()\n"
"  restrtcd = fvsRestartLastStand()\n"
"  fn = fvsGetKeywordFileName()\n"
"  rtnCode = fvsSetRtnCode()\n"
"  rtnCode = fvsGetRtnCode()\n"
"  ISTOPDONE = fvsStopPoint(LOCODE)\n"
"  ISTOPDONE = getAmStopping()\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  test_error = PyErr_NewException ("test.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));












/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"test");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
