      SUBROUTINE UPKEY (KEYWRD)
      IMPLICIT NONE
C----------
C  $Id: upkey.f 767 2013-04-10 22:29:22Z rhavis@msn.com $
C----------
C  THESE ROUTINES CONVERT KEYWORDS THAT ARE INPUT IN LOWER CASE LETTERS
C  TO UPPER CASE LETTERS.
C----------
      INTEGER I
      CHARACTER*8 KEYWRD
      DO 40 I=1,8
      CALL UPCASE(KEYWRD(I:I))
   40 CONTINUE
      RETURN
      END
