# This file is automatically generated during packaging.
# The version is extracted from the current Git tag using setup.py version.

__version__ = '0.0.11'
__status__ = 'alpha'
__git_tag__ = ''

# TODO: Add git commit