module arrays_mod
    use prgprm_mod
    implicit none
!CODE SEGMENT ARRAYS
!----------
!  **ARRAYS DATE OF LAST REVISION:  04/10/2009
!----------
      INTEGER ICR(MAXTRE),IMC(MAXTRE),IND(MAXTRE),IND1(MAXTRE),   &
            IND2(MAXTRE),ISP(MAXTRE),ITRE(MAXTRE),ITRUNC(MAXTRE), &
            NORMHT(MAXTRE),DEFECT(MAXTRE),IDTREE(MAXTRE),         &
            ISPECL(MAXTRE),KUTKOD(MAXTRE),DAMSEV(6,MAXTRE)
      REAL ABIRTH(MAXTRE),BFV(MAXTRE),CFV(MAXTRE),HT2TD(MAXTRE,2), &
            DBH(MAXTRE),DG(MAXTRE),HT(MAXTRE),                     &
            OLDRN(MAXTRE),OLDPCT(MAXTRE),PCT(MAXTRE),PROB(MAXTRE), &
            WK1(MAXTRE),WK2(MAXTRE),WK3(MAXTRE),WK4(MAXTRE),       &
            WK5(MAXTRE),WK6(MAXTRE),ZRAND(MAXTRE),                 &
            PLTSIZ(MAXTRE),HTG(MAXTRE),CRWDTH(MAXTRE),YRDLOS(MAXTRE)
!----------
!  VECTORS IN THE ARRAYS COMMON AREA STORE INDIVIDUAL TREE ATTRIBUTES.
!  ALL OF THESE VECTORS ARE MODIFIED OR DESTROYED WHEN **COMPRS**
!  IS CALLED TO COMPRESS THE TREE LIST.  ALSO, THE CONTENTS OF THESE
!  VECTORS IS REARRANGED WHEN **TREDEL** IS CALLED TO DELETE TREE
!  RECORDS.
!----------
!
!       BFV -- CURRENT BOARD FOOT VOLUME.  THIS IS THE VOLUME OF A
!              TREE, AND HAS NOT BEEN EXPANDED TO VOLUME PER ACRE.
!              CALCULATED IN **VOLS**.
!       CFV -- CURRENT TOTAL CUBIC VOLUME (VOLUME PER TREE AS ABOVE).
!              CALCULATED IN **VOLS**.
!       DBH -- TREE DIAMETER AT THE BEGINNING OF A PROJECTION CYCLE.
!              READ IN **INTREE**, INCREMENTED IN **UPDATE** AT END OF
!              CYCLE.
!    DEFECT -- PERCENT DEFECT CODED AS 11223344 WHERE:
!                 11 = INPUT MC DEFECT PERCENT
!                 22 = INPUT BF DEFECT PERCENT
!                 33 = MC DEFECT % USED FOR A GIVEN CYCLE
!                 44 = BF DEFECT % USED FOR A GIVEN CYCLE
!              11 AND 22 ARE LOADED IN **BASDAM**
!              33 AND 44 ARE COMPUTED AND USED IN **VOLS**
!              33 AND 44 ARE PRINTED IN **PRTRLS**
!    DAMSEV -- STORES DAMAGE/SEVERITY CODES DURING PROCESSING OF INPUT TREE
!              DATA FOR USE AT END OF KEYWORD PROCESSING. USED ONLY DURING
!              INITIALIZATION.
!        DG -- PREDICTED PERIODIC DIAMETER INCREMENT.  READ IN
!              **INTREE**, AND AT INPUT IT MAY BE AN INCREMENT OR A PAST
!              OR FUTURE DIAMETER MEASUREMENT.  COMPUTED IN **DGF** AND
!              **DGDRIV** EACH CYCLE.
!        HT -- TREE HEIGHT AT THE BEGINNING OF A PROJECTION CYCLE.
!              READ IN **INTREE** (OPTIONAL INPUT), INCREMENTED IN
!              **UPDATE** AT END OF CYCLE.
!   HT2TD -- IS THE HEIGHT FROM STUMP TO SECIFIED TOP DIAMETER.
!              HT2TD(  ,1)= CF MERCH TOP, HT2TD(  ,2)= BF MERCH TOP
!              SET IN VARVOL IT IS REPORTED IN THE DBS CUT LIST TABLE
!              IF IT=-1 CALL IS FROM FMSVOL (ENTRY FMSVL2) TO CALCULATE
!              SNAG VOLUME OR FROM FMCROWW. DON'T LOAD HT2TD IN THAT CASE
!       HTG -- PREDICTED PERIODIC HEIGHT INCREMENT.  CALCULATED EACH
!              CYCLE IN **HTGF**.
!    CRWDTH -- PREDICTED CROWN WIDTH. CALCULATED EACH CYCLE IN **CWIDTH**.
!    ISPECL -- SPECIAL TREE STATUS CODE USED TO FLAG TREES FOR SPECIFIC
!              REASONS SUCH AS WILDLIFE TREES, ETC. CODE CAN BE USED IN
!              SETTING CUT PRIORITY VIA MULTIPLIER ON TCONDMLT KEYWORD.
!    OLDPCT -- PERCENTILE IN THE DISTRIBUTION OF TREE BASAL AREA IN
!              THE PREVIOUS CYCLE.  ASSIGNED IN **TREGRO** AT THE END
!              OF EACH CYCLE.
!     OLDRN -- RANDOM ERROR ASSIGNED TO TREES IN THE PREVIOUS CYCLE.
!       PCT -- PERCENTILE IN THE DISTRIBUTION OF TREE BASAL AREA.
!              COMPUTED IN **DENSE**.  IF STAND IS THINNED PCT IS USED
!              IN **CUTS** AS TEMPORARY STORAGE FOR COMPUTING SUMMARY
!              DISTRIBUTIONS.  PERCENTILES ARE REASSIGNED IN CALL TO
!              **DENSE** FOLLOWING THINNING.
!    PLTSIZ -- THE SIZE OF PLOT ON WHICH THE TREE WAS MEASURED. SET IN
!              **NOTRE** FOR INVENTORY TREES, AND **ESTAB** FOR
!              ESTABLISHED TREES.
!      PROB -- NUMBER OF TREES PER ACRE REPRESENTED BY THE TREE RECORD.
!              READ IN **INTREE**; AT INPUT INTERPRETED AS NUMBER OF
!              TREES REPRESENTED BY THE TREE RECORD.  CONVERTED TO
!              TREES PER ACRE IN **NOTRE**.  MODIFIED TO REFLECT
!              THINNING IN **CUTS** AND MORTALITY IN **UPDATE**.
!       WK1 -- WORK ARRAY.  DURING CALIBRATION, WK1 IS USED TO STORE
!              THE DIFFERENCE BETWEEN PREDICTED AND OBSERVED DBH
!              INCREMENT IN **DGDRIV** AND THE RATIO OF PREDICTED
!              TO OBSERVED HEIGHT INCREMENT IN **REGENT**.  IN
!              **DGDRIV**, WK1 IS LOADED WITH PAST 10-YEAR DBH
!              INCREMENT FOR USE IN **MORTS**.  IN **VOLS**, WK1 IS
!              LOADED WITH MERCHANTABLE CUBIC FOOT VOLUME FOR USE
!              IN **CUTS** IN THE NEXT CYCLE.
!       WK2 -- WORK ARRAY.  USED WITHIN **CUTS** TO HOLD CUTTING
!              PRIORITY LEVELS AND THEN CFV REMOVED.  USED WITHIN
!              **DENSE** TO HOLD D*D*PROB WHEN COMPUTING PERCENTILES
!              IN THE BASAL AREA DISTRIBUTION.  DURING CALIBRATION, WK2
!              IS USED TO PASS TREE DBH FROM **DGDRIV** TO **DGF**.
!              EACH PROJECTION CYCLE, IT IS LOADED WITH THE TREES PER
!              ACRE DYING IN **MORTS**.  THE MORTALITY ESTIMATE MAY BE
!              MODIFIED BY SUBSEQUENT INTERACTION WITH PEST MODELS.
!              WK2 IS SUBTRACTED FROM PROB IN **UPDATE** AND THEN
!              USED WITHIN **VOLS** TO HOLD CUFT VOL ACCRETION.
!       WK3 -- WORK ARRAY.  DURING CALIBRATION, WK3 IS USED TO
!              CARRY BACKDATED DBH FROM **DENSE** TO **DGDRIV**.
!              DURING EACH PROJECTION CYCLE, WK3 IS USED FREQUENTLY
!              AS WORK SPACE FOR COMPUTING PERCENTILES IN OUTPUT
!              DISTRIBUTIONS.  WK3 IS AVAILABLE FOR OTHER WORK
!              SPACE APPLICATIONS, BUT SHOULD NOT BE USED TO CARRY
!              DATA BETWEEN GROWTH ROUTINES.
!       WK4 -- ADDITIONAL WORK SPACE THAT IS CURRENTLY USED ONLY
!       WK5    WITHIN CUTS (AND WK4 THIS HOLDS CLIMATE GROWTH MULTIPLIERS
!              FOR EACH TREE).  WK4 IS LOADED WITH REMOVALS FROM TRIAL
!       WK6    THINNINGS, WK5 IS LOADED WITH REMOVED MERCHANTABLE
!              CUBIC FOOT VOLUME, AND WK6 IS LOADED WITH REMOVED
!              BOARD FOOT VOLUME.
!       ICR -- CROWN LENGTH EXPRESSED AS A PERCENTAGE OF TOTAL HEIGHT.
!              OPTIONAL INPUT VARIABLE, READ IN **INTREE**.  MISSING
!              VALUES ARE DUBBED IN **CROWN** OR **DUBSCR**, DEPENDING
!              ON TREE SIZE.  IF TREE HAS LESS THAN 3 IN. DBH, CROWN
!              DOES NOT CHANGE.  WHEN DBH CROSSES  3 IN. THRESHOLD, A
!              NEW CROWN RATIO IS ASSIGNED IN **DUBSCR**.  ALL CROWN
!              RATIOS FOR TREES WITH GREATER THAN 3 IN. DBH ARE UPDATED
!              EACH CYCLE IN **CROWN**.
!       IMC -- TREE VALUE CLASS.  READ IN **INTREE**, USED IN **CUTS**
!              TO COMPUTE REMOVAL PRIORITY (1=DESIRABLE, 2=ACCEPTABLE,
!              3=LIVE CULL).
!       IND -- POINTERS USED TO SORT THE TREE LIST IN ORDER OF
!              DESCENDING DIAMETER (IF IND(I)=1, TREE I IS THE
!              LARGEST TREE IN THE STAND).  INITIALLY LOADED IN
!              **IDSORT** WITH A CALL FROM **CRATET**.  UPDATED EACH
!              CYCLE WITH CALL TO **IDSORT** FROM **TREGRO**.
!      IND1 -- USED TO ACCESS THE TREE LIST IN SPECIES ORDER.  IND1
!              IS DIVIDED INTO SECTORS SUCH THAT EACH SECTOR
!              CONTAINS INDICES TO THE INPUT ORDER OF ALL THE
!              RECORDS OF A GIVEN SPECIES.  IND1 MUST BE REFERENCED
!              WITH THE ARRAY ISCT (DIMENSIONED MAXSP,2).  THERE ARE
!              2 ELEMENTS IN ISCT FOR EACH SPECIES.  THE FIRST
!              ELEMENT (ISCT(I,1)) POINTS TO FIRST RECORD IN THE
!              SECTOR OF IND1 THAT IS ASSOCIATED WITH SPECIES I;
!              THE SECOND ELEMENT (ISCT(I,2)) POINTS TO THE LAST
!              RECORD IN THE SECTOR OF IND1 THAT IS ASSOCIATED
!              WITH SPECIES I.  IF THERE ARE NO RECORDS FOR SPECIES
!              I, ISCT(I,1) AND ISCT(I,2) WILL HAVE VALUES OF 0.
!              IND1 AND ISCT ARE INITIALLY COMPUTED WITH A CALL TO
!              **SETUP** FROM **MAIN**.  THEY ARE RECOMPUTED IN
!              **CRATET** WHEN NON-PROJECTABLE RECORDS ARE DELETED.
!              WHEN RECORDS ARE TRIPLED, THEY ARE RECOMPUTED WITH
!              CALL TO **REASS** FROM **TREGRO.  THEY ARE RECOMPUTED
!              BY **SPESRT** AND **SETUP** ANYTIME TREE RECORDS ARE
!              COMPLETELY REMOVED IN THINNING (CALL FROM **CUTS**),
!              THE NUMBER OF TREE RECORDS IS CHANGED BY COMPRESSION
!              (CALL FROM **COMCUP), OR NEW TREE RECORDS ARE
!              CREATED BY THE REGENERATION ESTABLISHMENT MODEL
!              (CALL FROM **ESNUTR**).
!      IND2 -- POINTER WORK ARRAY. IT IS USED IN CHAIN SORTING BY
!              **INTREE** AND **SETUP** AND CANNOT BE REDEFINED
!              BETWEEN CALLS TO THESE ROUTINES.  DURING CALIB. IT IS
!              USED BY **DGDRIV** TO FIND THE MEDIUM OF THE BAI
!              DISTRIBUTION (WK1). FOLLOWING CALIBRATION IT IS USED
!              BY **CRATET** TO STORE POINTERS TO THE TREES WITH
!              MISSING HEIGHTS, THEN, AFTER THE HEIGHTS ARE DUBBED
!              IT HOLDS THE POINTERS TO MISSING CROWN RATIOS AND IS
!              PASSED TO **CROWN**.  DURING NORMAL CYCLING,  IT  IS
!              USED  BY  **HTGF**  TO  STORE  POINTERS TO THE SMALL
!              TREES; **REGENT** USES THIS LIST TO INDEX THE  TREES
!              IT IS RESPONSIBLE FOR GROWING.  IND2 IS USED WITHIN
!              **CUTS** TO INDEX WK2 AND WITHIN  **REASS**  IN  THE
!              REALLIGNMENT PROCESSING OF IND AND IND1.
!       ISP -- SPECIES CODE FOR THE ITH TREE.  READ IN **INTREE**,
!              CONVERTED TO NUMERIC CODE IN **SETUP**.
!      ITRE -- DECODED PLOT TRANSECT NUMBER. RECORD TRIPLED.
!    ITRUNC -- THE HEIGHT OF TRUNCATION FOR TREES WHICH HAVE BEEN
!              TOPKILLED.
!    NORMHT -- THE EXPECTED HEIGHT (AS PREDICTED BY THE HEIGHT-
!              DIAMETER CURVE) OF TREES WHICH HAVE BEEN TOPKILLED.
!    KUTKOD -- FLAG DESIGNATING TREE STATUS IF THE PRESCRIPTION THIN
!              METHOD IS USED.
!    IDTREE -- ARRAY TO HOLD INDIVIDUAL TREE IDS. LOADED IN INTREE.
!    ABIRTH -- ARRAY TO HOLD YEAR OF BIRTH OF THE TREE OR TREE AGE.
!     ZRAND -- ARRAY THAT HOLDS THE CORRELATION OF DIAMETER INCREMENT
!              ERRORS.
!    YRDLOS -- ARRAY HOLDING THE PROPORTIONAL REDUCTION IN
!              VOLUME DUE TO YARD LOSS FOR A GIVEN TREE
!              RECORD FOR A CYCLE. LOADED IN **CUTS**. PASSED TO THE
!              TREELIST AND FVSSTAND OUTPUT FILES FOR USE IN
!              POST-PROCESSING PROGRAMS.
!
!-----END SEGMENT

end module arrays_mod
