module calcom_mod
    implicit none
!ODE SEGMENT CALCOM
!----------
!  **CALCOM DATE OF LAST REVISION:  02/29/07
!----------
      INTEGER ISPHAB,ISPFOR,ISPDSQ,ISPCCF,IRHHAB,ICRHAB,NCALHT
      REAL    REGCH,POTEN,HGHCH,REIN(2),GMULT(2),FNMIN
      COMMON / CALCOM /  ISPHAB,ISPFOR,ISPDSQ,ISPCCF,REGCH,IRHHAB, &
                         POTEN,HGHCH,REIN,GMULT,ICRHAB,FNMIN,NCALHT
!----------
!  DEFINITIONS OF VARIABLES IN 'CALCOM' COMMON BLOCK:
!----------
!
!    FNMIN  -- MINIMUM DIA. GROWTH OBSERVATIONS PER SPECIES TO
!              CALIBRATE LARGE TREE DIAMETER INCREMENT MODEL FOR
!              LOCAL CONDITIONS - USED IN DGDRIV ROUTINES
!    NCALHT -- MINIMUM NUMBER OF HEIGHT GROWHT OBSERVATIONS TO
!              CALIBRATE THE SMALL TREE HEIGHT INCREMENT MODEL FOR
!              LOCAL CONDITIONS - USED IN REGENT ROUTINES
!-----END SEGMENT
end module calcom_mod