module escomn_mod
    use prgprm_mod, only: mxfrcds,maxsp
    use esparm_mod, only: ndbhcl,nspspe
    !ODE SEGMENT ESCOMN
    !----------
    !   **ESCOMN  DATE OF LAST REVISION:   08/22/2012
    !----------
    INTEGER IFORST(MXFRCDS),IFORCD(MXFRCDS),NNID,IPREP,IHAB,IPHY, &
            ISPSPE(NSPSPE)
    !
    REAL    XMIN(MAXSP),OCURNF(MXFRCDS,MAXSP),OCURHT(16,MAXSP), &
            BNORML(20),HHTMAX(MAXSP),XCOS,XSIN,SLO,BWB4,BAA,BAASQ, &
            BAALN,ELEVSQ,REGT,BWAF,TIME,SQREGT,SQBWAF,XCOSAS, &
            XSINAS,DBHMID(NDBHCL),SUMPX(MAXSP),SUMPI(MAXSP)
    !
    !     COMMON AREA TO USE WITH ALL REGENERATION MODEL VARIANTS.
    !     BE SURE TO INCLUDE ESPARM BEFORE ESCOMN.
    !     USED IN ESADVH, ESBLKD, ESDLAY, ESGENT, ESNSPE, ESPADV, ESPREP, ESPSUB,
    !     ESPXCS, ESSUBH, ESTAB, ESTIME, ESTOCK, ESTPP, ESTUMP, & ESUCKR.
    !
    !-----END SEGMENT
end module escomn_mod
