module eshap_mod
    use prgprm_mod
    implicit none
    !CODE SEGMENT ESHAP
    !----------
    !  **ESHAP  DATE OF LAST REVISION:  01/16/02
    !----------
    !
          LOGICAL LINGRW,LAUTAL,LSPRUT
          INTEGER IPHYS(MAXPLT),IPHAB(MAXPLT),IPTIDS(MAXPLT),IPPREP(MAXPLT), &
                  IALN(3),IHABT(16),NPTIDS,IPRINT,INADV,LOAD,IDSDAT,MODE, &
                  KDTOLD,IHTYPE,IYRLRM,IFO,JOREGT,IBLK,METH,MINREP,IPINFO, &
                  ITRNRM,NTALLY
          REAL    PASP(MAXPLT),PSLO(MAXPLT),SUMPRE(5),XESMLT(MAXSP), &
                  HTADJ(MAXSP),ZMECH,XTES,ESB,ESA,PMECH,PBURN,OLDTIM, &
                  CONFID,STOADJ,ZBURN,ESDRAW,THRES1,THRES2
    !
    !     COMMON AREA TO BE USED WITH ALL REGENERATION MODEL VARIANTS.
    !     BE SURE TO INCLUDE PRGPRM.F77 BEFORE ESHAP.
    !     USED IN ESCPRS, ESFLTR, ESIN, ESINIT, ESNUTR, ESOUT, ESBLKD,
    !     ESPLT1, ESPLT2, ESTAB, ESPADV, ESPSUB, ESPXCS, ESUCKR, & ESTUMP.
    !
    !      IHABT -- SUMMARY AND COUNT OF PLOT HABITAT TYPE
    !      IPHAB -- PLOT HABITAT TYPE CODE.
    !       PASP -- PLOT ASPECT IN RADIANS.  DEFAULT IS STAND ASPECT.
    !       PSLO -- PLOT SLOPE RATIO.  DEFAULT IS STAND SLOPE.
    !      IPHYS -- PLOT PHYSIOGRAPHIC POSITION.  DEFAULT IS MID-SLOPE.
    !     IPPREP -- PLOT SITE PREP.  TO USE VECTOR, 'LOAD' MUST EQUAL 1.
    !     IPRINT -- CONTROLS PRINTING OF ESTABLISHMENT SUMMARIES. 0=NOTHING
    !               PRINTED. 1=STAND SUMMARY.
    !      INADV -- WE ASSUME ADVANCE REGENERATION WAS INVENTORIED UNLESS
    !               'INADV' IS SET TO 1.  IF INADV=1, THE MODEL WILL ADD
    !               THE EXPECTED ADVANCE COMPONENT.
    !       LOAD -- A 0/1 VARIABLE TO INDICATE WHETHER TO USE SITE PREP
    !               FROM AN INVENTORY AS INPUT BY 'IPPREP'.  1= USE THE
    !               VECTOR IPPREP FROM PLOTINFO KEYWORD OR TREEDATA CARDS
    !     IDSDAT -- DATE OF DISTURBANCE.
    !      ZMECH -- DATE OF MECHANICAL SITE PREP.
    !      ZBURN -- DATE OF BURN SITE PREP.
    !     JOREGT -- OUTPUT UNIT FOR REGEN SUMMARY.  DEFINED IN ESINIT.
    !      HTADJ -- ADJUSTMENT VALUE FOR TREE HEIGHTS, BY SPECIES.
    !     CONFID -- CURRENTLY USED TO SET THE NUMBER OF EXCESS TREES PER
    !               SPECIES PASSED TO THE PROGNOSIS MODEL.
    !     STOADJ -- MULTIPLIER FOR THE PROBABILITY OF STOCKING.
    !     ITRNRM -- NUMBER OF TREE RECORDS TO SPROUT IN ESUCKR.
    !     LINGRW -- TRUE IF AUTO-INGROWTH IS BEING SIMULATED, FALSE IF NOT.
    !     LAUTAL -- TRUE IF AUTO-TALLIES ARE BEING INCLUDED.
    !     IYRLRM -- THE YEAR OF LAST REMOVAL...SET IN ESNUTR.
    !     NTALLY -- THE CURRENT TALLY NUMBER.
    !       XTES -- RATIO OF REMOVALS AS CALCULATED IN ESNUTR.
    !     THRES1 -- LOWER THRESHOLD OF REMOVALS THAT TRIGGERS ONE TALLY.
    !     THRES2 -- UPPER THRESHOLD OF REMOVALS THAT TRIGGERS A TALLY
    !               SEQUENCE.  BOTH THRES1 & THRES2 ARE RATIOS.
    !     LSPRUT -- TRUE IF SPROUTING LOGIC IS ON, FALSE IF OFF.
    !
    !-----END SEGMENT
end module eshap_mod
