module fmsvcm_mod
    use svdata_mod, only: mxsvob
    implicit none
    !CODE SEGMENT FMSVCM
    !----------
    !  $Id: FMSVCM.F77 767 2013-04-10 22:29:22Z rhavis@msn.com $
    !----------
    !  **FMSVCM FIRE
    !----------
    !
    !     THIS COMMON AREA IS USED ONLY BY FMSVOUT-RELATED ROUTINES, INCLUDING
    !     FMSVTOBJ, FMSVOUT, FMSVFL, AND FMSVTREE
    !
    !     NOTE: NONE OF THESE VARIABLES NEED TO BE SAVED BY THE PPE!!!
    !
    !     THE FMY1 AND FMY2 ARRAYS CONTAIN POINTS SPECIFYING WHERE THE FIRE
    !     LINE IS.  IN THE CURRENT MODEL, THE POINTS ARE EQUALLY SPACED ACROSS
    !     THE PLOT, AND EACH VALUE REPRESENTS A Y-VALUE AVERAGE HALF-WAY
    !     TO THE NEXT POINT.
    !
          INTEGER    NFLPTS
          PARAMETER (NFLPTS=20)
          REAL       FMY1(NFLPTS),FMY2(NFLPTS),OFFSET(NFLPTS), &
                     CATCHUP(NFLPTS),FLPART,FLAMEHT
          INTEGER    IFMTYP,IOBJTPTMP(MXSVOB),IS2FTMP(MXSVOB)
    !
    !     TIOBJTP= A VECTOR USED FOR TEMPORARY COPY OF THE IOBJTP VECTOR ABOVE.
    !     TIS2F= A VECTOR USED FOR TEMPORARY COPY OF THE IS2F VECTOR BELOW.
    !
    !-----END SEGMENT
end module fmsvcm_mod
