module htcal_mod
    use prgprm_mod, only : maxsp
    implicit none
    !CODE SEGMENT HTCAL
    !----------
    !  **HTCAL  DATE OF LAST REVISION:  06/14/00
    !----------
          LOGICAL LHCOR2,LHTCAL(MAXSP)
          REAL    FINTH,HCOR2(MAXSP),HSIG(MAXSP)
          INTEGER IFINTH,IHTG
    !----------
    !  HEIGHT GROWTH CALIBRATION COMMON /HTCAL/
    !----------
    !     FINTH = MEASURMENT PERIOD FOR SMALL TREE HEIGHT GROWTH.
    !     HCOR2 = USER SUPPLIED CORRECTION TERMS...TO CORRECT THE
    !             HEIGHT GROWTH MODELS PRIOR TO CALIBRATION.
    !     HSIG  = DUMMY...MAY BE USED FOR SIGMAS.
    !     IFINTH= INTEGER VERSION OF FINTH.
    !     IHTG  = THE HEIGHT GROWTH VERSION OF IDG.
    !     LHCOR2= TRUE IF HCOR2 IS TO BE USED TO MODIFY HEIGHT GROWTH
    !             MODELS. SET FALSE IN GRINIT.
    !     LHTCAL= TRUE IF HEIGHT GROWTH CALIBRATION IS TO BE DONE,
    !             SET TRUE IN GRINIT.
    !-----END SEGMENT
end module htcal_mod
