module outcom_mod
    use prgprm_mod
    implicit none
!ODE SEGMENT OUTCOM
!----------
!  **OUTCOM DATE OF LAST REVISION:   10/11/02
!----------
      CHARACTER*3 IOSPTT(4),IOSPBR(4),IOSPTV(4),IOSPMR(4),IOSPAC(4), &
            IOSPCT(4),IOSPCV(4),IOSPMC(4),IOSPBV(4),IOSPRT(4),       &
            IOSPMO(4),IONSP(6)
      CHARACTER*72 ITITLE
      COMMON /OUTCHR/ IOSPTT,IOSPBR,IOSPTV,IOSPMR,IOSPAC,IOSPCT,IOSPCV, &
            IOSPMC,IOSPBV,IOSPRT,IOSPMO,IONSP,ITITLE
      INTEGER*4 IOSUM(20,MAXCY1)
      INTEGER   IOICR(6)
      REAL      OACC(7),OBFCUR(7),OCVCUR(7),OMCCUR(7),       &
            OMORT(7),ONTCUR(7),ONTRES(7),OSPAC(4),OSPCT(4),  &
            OCVREM(7),OMCREM(7),ONTREM(7),OSPCV(4),OSPMO(4), &
            OBFREM(7),OSPRT(4),OSPTT(4),OSPBV(4),OSPMC(4),   &
            OSPBR(4),OSPMR(4),OSPTV(4),DBHIO(6),HTIO(6),     &
            DGIO(6),PCTIO(6),PRBIO(6)
!----------
!  DEFINITIONS OF NOMINAL PERCENTILE DISTRIBUTION VECTORS
!----------
!
!      OACC -- ACCRETION/ACRE/YEAR WITH DISTRIBUTION
!              COMPUTED IN **VOLS**
!    OBFCUR -- CURRENT BOARD FOOT VOLUME WITH DISTRIBUTION.
!              COMPUTED IN TREGRO
!    OBFREM -- BOARD FOOT VOLUME REMOVED IN THINNING WITH DISTRIBUTION.
!              COMPUTED IN **CUTS**
!    OCVREM -- TOTAL CUBIC VOLUME REMOVED IN THINNING WITH
!              DISTRIBUTION COMPUTED IN **CUTS**
!    OCVCUR -- CURRENT TOTAL CUBIC VOLUME WITH DISTRIBUTION
!              COMPUTED IN TREGRO
!    OMCCUR -- CURRENT MERCHANTABLE CUBIC VOLUME WITH DISPRIBUTION.
!              COMPUTED IN TREGRO
!    OMCREM -- MERCHANTABLE CUBIC VOLUME REMOVED IN THINNING WITH
!              DISTRIBUTION. COMPUTED IN **CUTS**
!     OMORT -- MORTALITY/ACRE/YEAR WITH DISTRIBUTION
!              COMPUTED IN **MORTS**
!    ONTCUR -- CURRENT NUMBER OF TREES WITH DISTRIBUTION
!              COMPUTED IN  **TREGRO**
!    ONTREM -- NUMBER OF TREES REMOVED IN THINNING WITH DISTRIBUTION
!              COMPUTED IN **CUTS**
!    ONTRES -- RESIDUAL NUMBER OF TREES FOLLOWING THINNING WITH
!              DISTRIBUTION COMPUTED IN **CUTS**
!----------
!  SPECIES-TREE CLASS COMPOSITION VECTORS
!----------
!
!    IOSPAC
!     OSPAC -- CORRESPONDING TO OACC
!    IOSPBV
!     OSPBV -- CORRESPONDING TO OBFCUR
!    IOSPBR
!     OSPBR -- CORRESPONDING TO OBFREM
!    IOSPCT
!     OSPCT -- CORRESPONDING TO ONTCUR
!    IOSPCV
!     OSPCV -- CORRESPONDING TO OCVCUR
!    IOSPMC
!     OSPMC -- CORRESPONDING TO OMCCUR
!    IOSPMR
!     OSPMR -- CORRESPONDING TO OMCREM
!    IOSPMO
!     OSPMO -- CORRESPONDING TO OMORT
!    IOSPRT
!     OSPRT -- CORRESPONDING TO ONTRES
!    IOSPTT
!     OSPTT -- CORRESPONDING TO ONTREM
!    IOSPTV
!     OSPTV -- CORRESPONDING TO OCUREM
!     IONSP -- EXAMPLE TREE RECORD'S SPECIES AND TREE CLASS
!     DBHIO -- EXAMPLE TREE RECORD'S DBH
!      HTIO -- EXAMPLE TREE RECORD'S HT
!     IOICR -- EXAMPLE TREE RECORD'S ICR
!      DGIO -- EXAMPLE TREE RECORD'S DG
!     PCTIO -- EXAMPLE TREE RECORD'S PCT
!     PRBIO -- EXAMPLE TREE RECORD'S PROB
!     IOSUM -- THE SUMMARY OUTPUT STORED BY CYCLE(41) AND
!              ATTRIBUTE(17)--THE ATTRIBUTES ARE LISTED IN **SUMOUT**
!    ITITLE -- A 72 CHAR TITLE.
!-----END SEGMENT

end module outcom_mod
