module plot_mod
    use prgprm_mod
    implicit none
!CODE SEGMENT PLOT
!----------
! COMMON $ID$
!----------
!xxf2py character, intent(c) :: jsp(4,maxsp)
      CHARACTER*4 MGMID,JSP(MAXSP),NSP(MAXSP,3),FIAJSP(MAXSP)
      CHARACTER*10 CPVREF
      CHARACTER*6 PLNJSP(MAXSP)
      CHARACTER*26 NPLT
      CHARACTER*40 DBCN
      REAL    ASPECT,AVH,BA,BAF,BRK,ATAVD,ATAVH,ATBA,ATCCF,ATTPA,COVYR, &
            COVMLT,ELEV,FINT,FPA,GROSPC,PI,RELDEN,RELDM1,OLDTPA,        &
            RELDSP(MAXSP),RMSQD,SLOPE,SAMWT,TFPA,RMAI,TPROB,OLDBA,      &
            SITEAR(MAXSP),OLDAVH,ORMSQD,SDIMAX,SDIDEF(MAXSP),           &
            BARANK(MAXSP),TLAT,TLONG,PMSDIL,PMSDIU,VMLT,VMLTYR,         &
            BTSDIX,ATSDIX,SDIBC,SDIAC,SITETR(MAXSTR,6),STNDSI,          &
            SDIBC2,SDIAC2
      INTEGER IPTINV,NONSTK,IAGE,IFINT,IFOR,IGL,IPVEC(MAXPLT),ISMALL, &
            ITYPE,JTYPE(122),ISISP,ISLOP,IASPEC,KODTYP,KODFOR,MANAGD, &
            IMODTY,IPHREG,IFORTP,ISZCL,ISTCL,ISTATE,ICNTY,ICAGE,      &
            NSITET,JSPIN(MAXSP),JSPINDEF
!----------
!  DEFINITIONS OF VARIABLES IN 'PLOT' COMMON BLOCK:
!----------
!
!    ASPECT -- STAND ASPECT; READ IN DEGREES, CONVERTED TO RADIANS.
!    IASPEC -- INPUT STAND ASPECT IN DEGREES.
!       AVH -- CURRENT AVERAGE STAND HEIGHT. CALCULATED IN **DENSE**.
!        BA -- CURRENT STAND BASAL AREA.  CALCULATED IN **DENSE**.
!       BAF -- BASAL AREA FACTOR USED IN INVENTORY.  DEFAULTED
!              TO 40 IN **BLOCK DATA**, BUT CAN BE ALTERED BY
!              KEYWORD.
!       BRK -- MINIMUM DIAMETER OF TREES MEASURED ON VARIABLE PLOT.
!              SET TO 5 IN **INITRE**, BUT CAN BE RESET BY
!              KEYWORD.
!        D0
!    D0MULT -- PARAMETERS FOR THE SWITCHING FUNCTION IN MORTS.
!              SET IN GRINIT, CAN BE RESET BY KEYWORD.
!      DBCN -- DATABASE CONTROL NUMBER, USED BY THE DATABASE EXTENSION
!              FOR DATA SOURCE IDENTIFICATION AT THE STAND LEVEL.
!     ATAVD -- QUADRATIC MEAN STAND DBH. AFTER THINNING. SAVED IN
!              GRINCR AFTER CALLING DENSE.
!     ATAVH -- AVERAGE HEIGHT OF DOMINATES AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!      ATBA -- BASAL AREA AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!     ATTPA -- TREES PER ACRE AFTER THINNING.
!              SAVED IN GRINCR AFTER CALL TO DENSE.
!    COVMLT -- SUM OF SERIAL CORRELATIONS BETWEEN BETWEEN TWO PERIODS
!              OF LENGTH I AND J.
!     COVYR -- COVMLT(YR,YR).
!    CPVREV -- POTENTIAL VEGETATION REFERENCE CODE USED IN **HABTYP**
!      ELEV -- STAND ELEVATION IN HUNDREDS OF FEET.
!      FINT -- FLOATING POINT REPRESENTATION OF LENGTH OF CURRENT
!              CYCLE.  INITIALIZED IN **INITRE**,UPDATED IN **DISPLY**
!       FPA -- INVERSE OF THE AREA OF THE FIXED PLOT IN ACRES.
!              SET TO 300 IN **INITRE**, BUT CAN BE RESET BY
!              KEYWORD.
!    GROSPC -- MULTIPLIER WHICH INFLATES CROWN COMPETITION FACTOR
!              TO COMPENSATE FOR NON-STOCKABLE POINTS.  COMPUTED
!              IN **INITRE**.
!        PI -- NUMBER OF POINTS INVENTORIED.  SET IN **INITRE**.
!    IPTINV -- SAME AS PI (EXCEPT IT IS AN INTEGER)
!    NONSTK -- NUMBER OF NON-STOCKABLE POINTS INVENTORIED. SET
!              AND USED IN **INITRE**.
!    RELDEN -- CURRENT CROWN COMPETITION FACTOR FOR THE STAND.
!              COMPUTED IN **DENSE**.
!    RELDM1 -- CROWN COMPETITION FACTOR FOR STAND IN PREVIOUS CYCLE.
!              COMPUTED IN **DENSE**.
!    RELDSP -- CONTRIBUTION TO CROWN COMPETITION FACTOR OF EACH
!              SPECIES.  COMPUTED IN **DENSE**.
!     RMSQD -- STAND QUADRATIC MEAN DIAMETER.  CALCULATED IN
!              **DENSE**
!     SLOPE -- STAND SLOPE PERCENT SCALED TO THE RANGE 0-1.
!     ISLOP -- INPUT STAND SLOPE NOT DECODED.
!      TLAT -- INPUT STAND LATITUDE.
!     TLONG -- INPUT STAND LONGITUDE.
!      RMAI -- ADJUSTED MEAN ANNUAL INCREMENT FOR THE STAND
!    SITEAR -- SITE INDEX VALUES BY SPECIES FOR LARGE AND SMALL TREES.
!     ISISP -- SITE SPECIES IE SPECIES OF MAXIMUM BASAL AREA. SPECIFIED
!              BY KEYWORD OR CALCULATED IN MBACAL.
!    SITETR -- TREE INFORMATION FOR CALCULATING SITE INDEX:
!              1 = SPECIES
!              2 = DBH
!              3 = HEIGHT
!              4 = AGE
!              5 = TOTAL AGE OR BREAST HEIGHT AGE
!              6 = ON PLOT / OFF PLOT SITE TREE
!    NSITET -- NUMBER OF SITE TREES READ IN THE INPUT DATA.
!    SDIMAX -- MAXIMUM STAND DENSITY INDEX FOR THE STAND.
!    SDIDEF -- MAXIMUM STAND DENSITY INDEX FOR INDICATED SPECIES.
!    STNDSI -- INITIAL SITE INDEX OF THE SITE SPECIES FOR THE STAND;
!              INITIALLY SET IN INITRE; POSSIBLY RESET IN GRINCR.
!    BARANK -- SPECIES RANKING BY AMOUNT OF BASAL AREA.
!    PMSDIL -- PERCENT VALUE OF MAX SDI WHERE DENSITY RELATED MORTALITY
!              IS INVOKED.
!    PMSDIU -- PERCENT VALUE OF MAX SDI AT WHICH STAND REACHES MAXIMUM
!              DENSITY.
!     SAMWT -- STAND SAMPLING WEIGHT. USED ONLY TO PASS THE SAMPLING
!              WEIGHT FOR THE STAND TO THE NEXT STEPS IN ANY ANALYSIS
!              VIA THE SUMMARY OUTPUT. SEE GROPTS & DISPLY FOR DETAILS.
!      TFPA -- SUM OF THE AREA OF A SET OF FIXED AREA PLOTS
!              WHICH ARE TO BE COMBINED AND RUN AS A SINGLE
!              STAND.  NORMALLY SET TO ZERO.
!     TPROB -- TOTAL NUMBER OF TREES PER ACRE.
!      IAGE -- ORIGINAL STAND AGE -- SHOULD NEVER BE UPDATED.
!     ICAGE -- ORIGINAL STAND AGE COMPUTED FROM SIZE CLASS & TREE HT
!     ICNTY -- FIA COUNTY CODE
!     IFINT -- FIXED POINT REPRESENTATION OF CURRENT CYCLE LENGTH.
!              LOADED IN **MAIN**.
!      IFOR -- SUBSCRIPT TO REGION ONE FOREST IDENTIFICATION CODE.
!       IGL -- GEOGRAPHIC LOCATION CODE: 1=NORTH, 2=CENTRAL,
!              3=SOUTH.  LOADED IN INITRE DEPENDING ON VALUE OF
!              IFOR, USED IN REGENT.
!     IPVEC -- SUB-PLOT IDENTIFICATION VECTOR.
!    ISMALL -- NUMBER OF TREE RECORDS LESS THAN 3.0 INCHES DBH.
!              COMPUTED IN **HTGF**.  SUBSCRIPTS TO THESE RECORDS
!              ARE STORED IN IND2.
!    ISTATE -- FIA STATE CODE
!     ITYPE -- INPUT STAND HABITAT TYPE CODE.  CONVERTED TO
!              SUBSCRIPT IN **INITRE**.
!       JSP -- VALID SPECIES CODES.  LOADED IN **BLOCK DATA**.
!              CHANGABLE BY KEYWORD.
!     JSPIN -- SET IN **INTREE**,**SPCTRN**,**ESTAB**, - CARRIES INPUT
!              SPECIES CODE FORMAT: 1=ALPHA CODE,2=FIA CODE,3=PLANTS CODE
!              DEFAULT SET IN **INTRE**, **SPCTRN**
!     JTYPE -- VALID HABITAT TYPE CODES.  LOADED IN **BLOCK DATA**.
!     MGMID -- THE RUN MANAGEMENT ID. SET BY KEYWORD.
!      NPLT -- STAND IDENTIFICATION CODE.  INPUT BY KEYWORD CARD.
!       NSP -- VALID SPECIES-TREE CLASS CODES.  LOADED IN
!              **BLOCK DATA**.
!    OLDTPA -- THE TREES PER ACRE AT THE END OF THE LAST CYCLE
!     OLDBA -- THE BASAL AREA PER ACRE AT THE END OF THE LAST CYCLE
!    OLDAVH -- AVERAGE DOM HEIGHT AT END OF LAST CYCLE.
!    ORMSQD -- QUADRATIC MEAN DBH AT END OF LAST CYCLE.
!      VMLT -- SUM OF SERIAL CORRELATIONS WITHIN A PERIOD OF LENGHT I
!    VMLTYR -- VMLT(YR)
!    KODTYP -- HABITAT TYPE CODE AS CLASSIFIED IN HABTYP
!    KODFOR -- USER FOREST CODE INTERPRETED IN FORCOD ROUTINE
!    MANAGD -- VARIABLE INDICATING WHETHER STAND IS CONSIDERED A
!              MANAGED STAND (0=UNMANAGED, 1=MANAGED)
!    BTSDIX -- MAXIMUM SDI BEFORE TREATMENT
!    ATSDIX -- MAXIMUM SDI AFTER  TREATMENT
!    IMODTY -- MODEL TYPE FOR THOSE VARIANTS THAT USE IT
!              FIELD 1 OF MODTYPE KEYWORD
!    IPHREG -- PHYSIOGRAPHIC REGION FOR THOSE VARIANTS THAT USE IT
!              FIELD 2 OF MODTYPE KEYWORD
!    IFORTP -- FOREST TYPE FOR THOSE VARIANTS THAT USE IT
!              FIELD 3 OF MODTYPE KEYWORD
!    ISZCL  -- SIZE CLASS CALCULATED IN STKVAL
!    ISTCL  -- STOCKING CLASS CALCULATED IN STKVAL
!    FIAJSP -- FIA SPECIES CODES CORRESPONDING TO SPECIES IN JSP.
!    PLNJSP -- PLANTS SPECIES SYMBOLS CORRESPONDING TO SPECIES IN JSP.
!     SDIAC -- STAND DENSITY INDEX FOLLOWING CUTTING
!     SDIBC -- STAND DENSITY INDEX BEFORE CUTTING
!    SDIAC2 -- ZEIDE STAND DENSITY INDEX FOLLOWING CUTTING
!    SDIBC2 -- ZEIDE STAND DENSITY INDEX BEFORE CUTTING
!  JSPINDEF -- DEFAULT SPECIES CODE FORMAT SET IN **INTREE** OR
!              **SPCTRN**
!-----END SEGMENT
end module plot_mod
