module workcm_mod
    use prgprm_mod
    implicit none
!CODE SEGMENT WORKCM
!----------
!  **WORKCM---COMMON   DATE OF LAST REVISION: 07/05/2007
!----------
      REAL    WORK1(MAXTRE),WORK2(MAXSP),WORK3(MAXTRE)
      INTEGER IWORK1(MAXTRE)
!----------
!  DEFINITIONS OF VARIABLES IN 'WORKCM' COMMON BLOCK:
!----------
!     NOTE: THIS COMMON BLOCK CONTAINS WORK ARRAYS WHICH WILL BE
!           AVAILABLE FOR USE IN VARIOUS PARTS OF THE MODEL.
!           THEIR USE SHOULD BE CLEARLY DOCUMENTED IN THE FOLLOWING
!           COMMENTS.
!
!     WORK1 -- USED IN **DGDRIV**, **PRTRLS**, AND **FVSSTD** IN
!              CALIBRATION (CYCLE 0) TO CARRY THE INPUT DIAMETER
!              GROWTHS FOR TREES WITH MEASURED DG, AND "0" FOR
!              TREES WITH NOMEASURED DG FOR PRINTING ON CYCLE 0
!              TREELIST. USED IN **EVLDX** TO PROCESS THE SPMCDBH
!              FUNCTION WHEN COVER IS BEING COMPUTED. USED IN
!              **SVCMP1,2,3**, **SVCUTS**, AND **SVMORT** TO STORE
!              INFORMATION ABOUT DELETED TREE RECORDS AND HOW MANY
!              OBJECTS RELATED TO EACH TREE HAVE BEEN CUT OR KILLED.
!              THESE ROUTINES ARE CALLED FROM **TREDEL** (**CUTS**),
!              **MORTS**, AND **COMPRS**
!
!     WORK2 -- USED IN **DGDRIV** TO PROCESS THE "MANAGED" KEYWORD
!
!     WORK3 -- USED LOCALLY IN **MORTS** TO CARRY THE END OF CYCLE
!              DIAMETERS FOR USE IN PROCESSING FIXMORT OPTIONS.
!
!    IWORK1 -- USED LOCALLY IN **MORTS** TO CARRY SORTED DIAMETER
!              INDICIES FOR USE IN PROCESSING FIXMORT OPTIONS.
!              BORROWED BY **MAIN** AND **INITRE** TO PROCESS THE
!              CYCLEAT KEYWORD.
!
!-----END SEGMENT
end module workcm_mod
